### ISSUE TITLE
Proposal: set condition type to any

### ISSUE THREAD

**Issue by faiwer** [KonstantinSimeonov/tsx-control-statements#10]
Hello. I have one tiny proposal. What about changing the typing for pseudo If-component's `condition` property from `boolean` to `any`.
 
Motivation:
```jsx
<If condition={!!(a && a.someField)}>...</If>
// =>
<If condition={a && a.someField}></If>
```
the same reason why we use `if (some)` instead of `if (Boolean(some))` or `if (!!(some))`

**Comment by KonstantinSimeonov** [comment]
sounds good

**Comment by wh1t3cAt1k** [comment]
I don't believe think this is a good idea in general, as losing type safety to `any` will render [some useful linting rules](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md) useless.

**Comment by faiwer** [comment]
I think there are few people who prefer to write `!!()`. Because the whole language doesn't work this way. E.g.:
- `if`
- `while`
- `repeat until`
- `array.filter` 
- `array.find`
- `array.some`

None of them ^ demands to have strictly boolean value. 

And TS itself always chooses practicality to strictness. 

To be honest I don't even know a language where developers has to write:
```
if (!!variable) {
}
```

Moreover actually it works unstrictly.

BTW we always can override default types. I did it in our projects.

**Comment by wh1t3cAt1k** [comment]
I am not entirely persuaded by this argument. I understand how reducing type safety can result in a more concise code, but I personally don't see concise code as the ultimate goal, especially when you lose something along the way.

Indeed one can do things very concisely in pure JS, at the expense of occasionally oneself in the foot, and the whole thing not being scalable as a result. Typing stuff as `any` is not really different from writing pure JS.

If we want to check that a variable is defined, and the `boolean` condition type (seemingly) makes it impossible, a we can always write a helper function called `isDefined(value: unknown)` and pass that into the condition. IMO it would much better communicate your intent while not circumventing the type safety.

**Comment by faiwer** [comment]
It may sound crazy :-) but what's about this:
```tsx
<IfStrict condition={mustBeBoolean>...</IfStrict>
<If condition={hasToBeTruthy}>...</If>
```

**Comment by perry-mitchell** [comment]
The value of `condition` should behave in the same way, imo, as any old `if` or conditional - testing truthiness. Forcing boolean values unnecessary creates this strict check which is overkill for most use cases, at least in my experience. Forcing consumers to use `!!` is ugly.

**Comment by KonstantinSimeonov** [comment]
done d7c8ac2
