### ISSUE TITLE
Integration with NuxtJS

### ISSUE THREAD

**Issue by juanfernandoe** [KonstantinSimeonov/tsx-control-statements#12]
Hi,

First of all, thank you for this amazing work.

Any idea how to integrate this with NutxJs + Typescript ?

**Comment by KonstantinSimeonov** [comment]
Hi, I've never used nuxt, but from I've read on their docs page, you can go one of two ways:
- Hook a typescript loader such as `ts-loader` or `awesome-typescript-loader` into nuxt [build config](https://nuxtjs.org/api/configuration-build) and hook `tsx-control-statements` as a transformer as shown [here](https://github.com/KonstantinSimeonov/tsx-control-statements/blob/master/examples/webpack/webpack.config.js#L23)
- Use [this integration](https://typescript.nuxtjs.org) and add the transformer to the `ts-loader` config described [here](https://typescript.nuxtjs.org/guide/setup.html#module-options) as is shown in the [examples]([here](https://github.com/KonstantinSimeonov/tsx-control-statements/blob/master/examples/webpack/webpack.config.js#L23)

Let me know if that worked out for you :)
