### ISSUE TITLE
ttypescript or ts-patch implementation

### ISSUE THREAD

**Issue by slikts** [KonstantinSimeonov/tsx-control-statements#151]
Currently tsx-control-statements has the same issue as AlexGilleran/jsx-control-statements#105 in that type narrowing is not supported, so using it with strict mode enabled will break in `tsc` and other tools like vscode. It should be possible to use [ttypescript] or [ts-patch] to add the control statements to `tsc` itself to improve tooling support; has this been considered?

[ttypescript]: https://github.com/cevek/ttypescript/tree/master/packages/ttypescript
[ts-patch]: https://github.com/nonara/ts-patch

**Comment by ghost** [comment]
> type checking occurs before the transformations occur, so at this point I don't believe a change in the emitted AST will affect type checking

I believe that's what https://github.com/nonara/ts-patch?tab=readme-ov-file#program-transformers are about: running the transformer before the typecheck

>  issues like this always remind me that I think such control statements do more harm than good.

I'm also skeptical about hijacking JSX/TSC conventions for conditionals. However, using different forms of conditionals is very unclean right now, too.
I wish conditionals were a better native JSX feature.

I wonder if this plugin should add a prefix like `__` (`<__If condition={...}>`) to hint that these aren't normal JSX.
