### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by Melazeta** [KonstantinSimeonov/tsx-control-statements#177]
I've installed this plugin with npm: `npm install tsx-control-statements`.

I have the following code:

```
<View>
    <If condition={true}>
        <Text>visible because condition is true</Text>
    </If>
    <If condition={false}>
        <Text>not visible because condition is false</Text>
    </If>
    <Choose>
        <When condition={true}>
            <Text>when</Text>
        </When>
        <Otherwise>
            <Text>otherwise</Text>
        </Otherwise>
    </Choose>
</View>
```

And in the application every single `<Text>` is visible, regardless of the condition being true or false or being inside the `<Otherwise>`.

Am I missing some kind of configuration?

**Comment by KonstantinSimeonov** [comment]
You probably didn't add the typescript transformer to your build configuration. What build tool are you using? Could you provide a link to the repo or an example for your build config?

**Comment by deathemperor** [comment]
How do I configure typescript transformer? I'm using Vite.
