### ISSUE TITLE
Variables defined with For tags are not recognized in typescript

### ISSUE THREAD

**Issue by kkorz** [KonstantinSimeonov/tsx-control-statements#225]
Here is the code example
![image](https://user-images.githubusercontent.com/88693424/185579173-b045db1a-d6a2-4f4c-a887-59583c7f80b1.png)

**Comment by KonstantinSimeonov** [comment]
this is related to the `With` component, not the `For. Unfortunately you have to do something like

```tsx
declare const createTime: DateTime
return (
  <For...
)
```

Another way to get around this would be to do:

```tsx
<For
  of={data}
  body={(each, index) => {
    const createTime = each?.call_log?.start_time
    return <Timeline.Item...
  }
/>
```

Explanation: the transformation occurs after typechecking, so even if I emit declarations for variables, static analysis tooling is still gonna complain :(
