### ISSUE TITLE
WARN issued when using the type-safe syntax in <For>

### ISSUE THREAD

**Issue by nippur72** [KonstantinSimeonov/tsx-control-statements#247]
when using the suggested type-safe version of `<For>`
```tsx
  <For of={list} body={el=><div></div>}/>
```
I get:
```
WARN(tsx-control-statements): "each" property of For is missing
```
Looking at the [source code](https://github.com/KonstantinSimeonov/tsx-control-statements/blob/d664a5c3fa1e3fa1d327726def3368c3194b297e/transformer.ts#L190), it seems that `each` is mandatory.

**Comment by KonstantinSimeonov** [comment]
It's not, but that's my buggy code for you :v: Gonna have some free time the next couple of days, will publish a fix and post here

**Comment by KonstantinSimeonov** [comment]
publish 5.1.1 which should get rid of the warning :headstone:
