### ISSUE TITLE
Crashes when comment is present right after the Control

### ISSUE THREAD

**Issue by tomitrescak** [KonstantinSimeonov/tsx-control-statements#6]
Hi, thanks for the last fix! I encountered an error which crashes the compiler when I have a comment right after the jsx control.

```
<If ...>
{/* comment */}
...
</If>
```

**Comment by faiwer** [comment]
Confirm it. I got it too in my code. Typescript crashes. Any comment as a nearest child to `<If/>` tag. Even when you wanna to temporally hide something :)

**Comment by KonstantinSimeonov** [comment]
This need more attention but the mentioned case has been fixed
