### ISSUE TITLE
<If/> doesn't set incremental keys

### ISSUE THREAD

**Issue by faiwer** [KonstantinSimeonov/tsx-control-statements#9]
Hello. I have found one thing that jsx-control-statements does in a different way than tsx-* does. JSX provides incremental keys for those nodes that don't have it. It allows us to write non-list items without excess key-properties.

Example:
```jsx
<If condition={true}>
    <div>1</div>
    <span>2</span>
    <strong>3</strong>
</If>
```
instead of this:
```jsx
<If condition={true}>
    <div key="div">1</div>
    <span key="span">2</span>
    <strong key="anything">3</strong>
</If>
```
tsx-control-statements:
![image](https://user-images.githubusercontent.com/744114/73459610-77e6b900-4377-11ea-9163-595bc930f125.png)

jsx-control-statements:
![image](https://user-images.githubusercontent.com/744114/73459631-7f0dc700-4377-11ea-9f59-113921d1beab.png)

this code:
```jsx
{true && <>
    <div>1</div>
    <span>2</span>
    <strong>3</strong>
</>}
```
doesn't have this problem because it doesn't use [], it uses React.Fragments:
![image](https://user-images.githubusercontent.com/744114/73459932-f17ea700-4377-11ea-9e6b-5eff4f534050.png)

I don't know what is the best way to avoid it, I think there're at least these two:
- automatically set incremental keys
- use fragment-wrapper (like in `true && <>` example)

I tried to do it in `transformer.js` by means this:
```js
return ts.createJsxFragment(
    ts.createJsxOpeningFragment(),
    ts.createConditional(condition, createExpressionLiteral(body), ts.createNull()),
    ts.createJsxJsxClosingFragment()
);
```
but it didn't help :) Actually I don't have experience with TS-AST :)
P.S. thanks for the library

**Comment by KonstantinSimeonov** [comment]
I'll see what I can do. I'd like to avoid setting keys, because they could potentially clash with user defined keys (it doesn't seem too likely though). Fragment is a nice solution but unfortunately it would cause problems for user with react versions that do not support fragments, so I'll probably go for keys in the end.

**Comment by KonstantinSimeonov** [comment]
Since 8a82ba4 a control statement with more than one child will result in a fragment instead of an array
